spring:
  application:
    name: Coffee-System
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/coffee_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:$Tomatemojado45}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true